### ISSUE TITLE
Mod quits shortly after starting the game

### ISSUE THREAD

**Issue by gozu** [uberhalit/EldenRingFpsUnlockAndMore#10]
Issue:

I just run the mod, it starts the game normally, then quits before the title screen.

This is with all the default Steam files, no modifications whatsoever.

Please let me know if I can provide you with a crash log.

Steam version of the game
Win11
nVidia GPU

**Comment by uberhalit** [comment]
Are you on the latest 0.0.0.2-beta?

**Comment by josmellop** [comment]
Mine quits too when I run the game.
Win 11, nvidia gpu, latest 0.0.0.2-beta

**Comment by uberhalit** [comment]
@josmellop Steam or non-steam version? What error message do you get?

**Comment by antisect** [comment]
here's what im getting if its of any use:

Source
EldenRingFPSUnlockAndMore

Summary
Stopped working

Date
‎25/‎02/‎2022 17:10

Status
Report sent

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	OMXIPWGY1YAPVMVZM4WRSNGUMM0QBBBG
Problem Signature 02:	0.0.0.2
Problem Signature 03:	b88fed76
Problem Signature 04:	System.ServiceProcess
Problem Signature 05:	4.8.4161.0
Problem Signature 06:	5e5e971c
Problem Signature 07:	73
Problem Signature 08:	196
Problem Signature 09:	System.InvalidOperationException
OS Version:	10.0.22000.2.0.0.256.48
Locale ID:	2057
Additional Information 1:	c412
Additional Information 2:	c412ae1ce00d37fd9e75065d7e86151e
Additional Information 3:	9664
Additional Information 4:	966492673f9743086584c8f35c99f05a

Extra information about the problem
Bucket ID:	d2318c2f15f529f0f79334d9946034a1 (1698759593550689441)

**Comment by gozu** [comment]
> Are you on the latest 0.0.0.2-beta?


No. Updating to 0.0.0.2-beta fixed it. Thanks for the fastest fix in history!

**Comment by josmellop** [comment]
> @josmellop Steam or non-steam version? What error message do you get?

Non-steam "non so legit" version. I don't get any error message. Only closes itself and desappear :(

**Comment by antisect** [comment]
mines steam version, no error message. Only closes itself and disappears

**Comment by josmellop** [comment]
> > @josmellop Steam or non-steam version? What error message do you get?
> 
> Non-steam "non so legit" version. I don't get any error message. Only closes itself and desappear :(

Indeed, steams open in console tab, but the application closes the moment the game opens.

**Comment by FowD8** [comment]
Same here, followed everything step by step, click "start game", game opens and the application just closes on itself when elden ring opens, nothing changes, still 60fps (legit steam game, changed all the proper files as instructed)

**Comment by DubbleClick** [comment]
fixed by pr #14

**Comment by ResistanceD3** [comment]
> Same here, followed everything step by step, click "start game", game opens and the application just closes on itself when elden ring opens with no error or anything, just closes, nothing changes, still 60fps (legit steam game, changed all the proper files as instructed)
> 
> (RTX 2080 Super)

Same issue here. Shuts down immediately. Not fixed in 0.0.0.2.

**Comment by DubbleClick** [comment]
reporting "Me too" is utterly pointless considering there's already a fix waiting...

**Comment by vadash** [comment]
Didnt fix. I had to fork and enable checkbox by default

**Comment by Billc200** [comment]
thanks man it work for me finally with your debug,cheers:)game runs so smooth now at 165 fps

**Comment by uberhalit** [comment]
Fixed with version 0.0.0.3
