### ISSUE TITLE
Does this work with the Online/Offline version of Steam? 

### ISSUE THREAD

**Issue by mfermin7** [uberhalit/EldenRingFpsUnlockAndMore#103]
I purchased this game from Steam and have about 100 hours in the game. I am worried about being banned from using this. Does this work Online/Offline version of Steam? If so, what do I do to make it work? I could care less about losing my runes and am more interested in better FPS.

**Comment by uberhalit** [comment]
Hello @mfermin7, 

as stated multiple times already all mods need to be run in offline mode, you can not use any mod/cheat online without risking a ban from EAC. You can however keep steam itself in online mode but you need to set the game to offline, then start the game without EAC through my utility.
