### ISSUE TITLE
Allow patching while game is already running

### ISSUE THREAD

**Issue by GoaLitiuM** [uberhalit/EldenRingFpsUnlockAndMore#11]
I need to run the game through Steam for custom Steam Controller presets to activate properly. If I run the game with the patcher, the default desktop preset will be used instead.

**Comment by GoaLitiuM** [comment]
I actually found a workaround for this: launch Steam Big Picture mode first and then run the game in patcher. You will get few errors regarding no access to the client but the patch seems to be working just fine.

**Comment by GoaLitiuM** [comment]
Is the game itself required to be run elevated for patching? I can workaround this issue by launching the Steam Big Picture mode and then run the game via patcher, but the mouse movement with the controller wont work with this method. I assume this is due to Steam running with normal user-level privileges and it's trying to simulate mouse movement in the game but the lack of access prevents moving the mouse in-game.

**Comment by uberhalit** [comment]
Just click "No" on the prompt of "Do you want to close and restart it in offline mode without EAC?". The patcher will use the running instance then. **Be aware however that if your game runs online or you forgot to disable EAC that you'll most likely get banned.**

**Comment by GoaLitiuM** [comment]
I'm not getting such prompt when I have the game already running (eldenring.exe renamed to start_protected_game.exe and launched via Steam).

**Comment by uberhalit** [comment]
Don't rename the exe, that alone won't disable EAC.

**Comment by GoaLitiuM** [comment]
Alright, now it worked:
- Launch Steam Big Picture
- Launch the game via "eldenring.exe", not via Steam (the game should load instantly with no EAC loading screen)
- Launch the patcher, click "No" when it asks you to close the game and restart it in offline mode
- The game should be patched at this point
