### ISSUE TITLE
Online Mode

### ISSUE THREAD

**Issue by heryoff** [uberhalit/EldenRingFpsUnlockAndMore#17]
Is there a way in the, hopefully near future, to use this on the online version of the game?
Or it is just impossible with the current anticheat?

**Comment by uberhalit** [comment]
The AntiCheat will most likely ban you. There are ways around that, but that would turn this utility (or at least its way of acting) into an online cheat. Tell FromSoft we don't have 2001 anymore and they should remove frame locks.
