### ISSUE TITLE
mod shuts down immediately after opening game

### ISSUE THREAD

**Issue by ResistanceD3** [uberhalit/EldenRingFpsUnlockAndMore#18]
Is there no way to fix?

**Comment by DubbleClick** [comment]
look at #14, it just needs a merge

**Comment by korb-oss** [comment]
@DubbleClick fix works, but the frame lock tick is greyed out and patch game button does nothing. Application is stuck in "reading game".

**Comment by DubbleClick** [comment]
Interesting, he removed the logic to enable the checkbox once a game is loaded. Just remove the IsEnabled property on the tick in the MainForm

**Comment by clawstheone** [comment]
I have this issue and I don't understand what I know to do to fix it. Using beta 0.0.0.2, please help me.

**Comment by ResistanceD3** [comment]
If there is a fix, why not just release 0.0.0.3? Or at least explain the fix properly for people that don't use this website every day.

**Comment by DubbleClick** [comment]
I'm not the owner of the repository so I can't tag a release. Either compiler yourself or wait for one to be tagged.

**Comment by uberhalit** [comment]
> If there is a fix, why not just release 0.0.0.3? Or at least explain the fix properly for people that don't use this website every day.

It has been stated very clearly that this is a pre-release. Don't expect everything to work nor expect 24/7 support from unpaid devs. This is open source so that people can fix issues themselves. Version 0.0.0.3 has been released (still a beta).
