### ISSUE TITLE
Ultra Wide Screen mode possible?

### ISSUE THREAD

**Issue by Laserstrahl** [uberhalit/EldenRingFpsUnlockAndMore#22]
Hey there!

Very good work! I tried to get the framerate unlocking to work for an hour now without success, however I was looking for a FoV Mod and that works perfectly! Thanks for that!

Is there a chance that Ultra-Wide-Screen can be supported by your mod? E.g. 3840x2160

That would be great! Shame on Fromsoftware that you modder-guys have to fix there software with features which are state of the art in 2022...

Cheers,
Laser

**Comment by uberhalit** [comment]
@Laserstrahl Version 0.0.0.5 hat jetzt support für Widescreen ;)
