### ISSUE TITLE
Camera fix planning?

### ISSUE THREAD

**Issue by MagicTearsAsunder** [uberhalit/EldenRingFpsUnlockAndMore#23]
First of all, thank you for your great job! I've used your mod for Sekiro and it was perfect, I am always recommending it.

Are you planning to add a camera fix as you made it for Sekiro? 

- disable camera auto rotate adjustment on movement (intended for mouse users)
- disable centering of camera (cam reset) on lock-on if there is no target

Thanks.

**Comment by Yoduh** [comment]
issue tracker isn't an appropriate place to make feature requests, but having said that, +10000000 this idea.  first thing I did in sekiro and DS3 was download mods to disable auto camera adjust and I'm really suffering now in Elden Ring without it.

shame the community has to do so much work to fix the obvious lack of care From puts into their PC ports, but praise our modders and praise the sun!

**Comment by lurch9** [comment]
big upvote

**Comment by TheAlgerian** [comment]
I didn't mind it that much in DS3 or Sekiro, in fact I never even noticed.
But this is an open world game, dammit! And it looks beautiful, why would they not want you to be able to look around freely?
Not to mention it screws you over big time when fighting giant enemies.

**Comment by Bourjois** [comment]
I'd just like to show my support for this. The camera (as well as the stuttering) is triggering motion sickness. I also used a free cam mod with Sekiro and it made a huge positive impact.

**Comment by uberhalit** [comment]
Added both camera fixes known from Sekiro to v1.1.0.0
