### ISSUE TITLE
Method not working

### ISSUE THREAD

**Issue by Snake93a** [uberhalit/EldenRingFpsUnlockAndMore#25]
Hello there,

I've did everything step by step, multiple times and I cant get more than 60 fps :(

Im using GeForce RTX 1660 Ti.

All the settings on the Nvidia has been done, both globally and manually to Elden Ring. Game is running without EAC, offline mode, borderless.

**Comment by uberhalit** [comment]
Hi, 
is your monitor running a high-refresh rate?
