### ISSUE TITLE
"Couldn't gain access to game process!"

### ISSUE THREAD

**Issue by justin-capalbo** [uberhalit/EldenRingFpsUnlockAndMore#26]
Hello,

I followed the steps to disable EAC and Nvidia steps. No matter whether I launch the game through the FPS unlocker or through steam, "Patch Game" remains grayed out and if I launch the game through the Unlocker tool, I get the warning "Couldn't gain access to game process!"

![image](https://user-images.githubusercontent.com/25281423/155843997-b9788c2f-bc61-4825-bd48-f903b573a961.png)

GPU is RTX 2070 super

**Comment by uberhalit** [comment]
Is your PC running in a restricted environment? Is tool running as administrator?
