### ISSUE TITLE
Level geometry not loading properly

### ISSUE THREAD

**Issue by dukedickem** [uberhalit/EldenRingFpsUnlockAndMore#27]
There are a lot of misplaced or outright missing walls in the levels with the unlocker enabled.
This is especially noticable at the site of grace in Murkwater Coast and when travelling down the Siofra River Well Depths elevator.
https://imgur.com/a/Kalm1WW

**Comment by FowD8** [comment]
turn off FoV changes, apparently it doesn't work as expected fully

**Comment by dukedickem** [comment]
Oh yeah that fixed it, thank you.

**Comment by uberhalit** [comment]
Fixed with v0.0.0.4
