### ISSUE TITLE
BUG - Couldn't find game installation path

### ISSUE THREAD

**Issue by starudream** [uberhalit/EldenRingFpsUnlockAndMore#3]
Possibly in the case of other languages, cannot be found 'ELDEN RING' in the registry.

In chinese, it is '艾尔登法环'.

![1](https://user-images.githubusercontent.com/16065307/155704744-db4c5b01-769f-4513-8e34-39cc60d1dffb.png)

https://github.com/uberhalit/EldenRingFpsUnlockAndMore/blob/9cdb040d4acb63e2522fa25381d88349ff0d2fdb/EldenRingFPSUnlockAndMore/MainWindow.xaml.cs#L94-L100

**Comment by starudream** [comment]
https://steamdb.info/app/1245620/info/

name_localized

lang|name
-- | --
schinese | 艾尔登法环
tchinese | 艾爾登法環

**Comment by badukov** [comment]
[EldenRingFPSUnlockAndMore_v0.0.0.1PathChoosingEdition.zip](https://github.com/uberhalit/EldenRingFpsUnlockAndMore/files/8141695/EldenRingFPSUnlockAndMore_v0.0.0.1PathChoosingEdition.zip)

I added manual folder selection if not found in the registry

**Comment by uberhalit** [comment]
@starudream Hi, 
you are right, I've added a prompt now to let the user choose the installation path themselves. Please tell me if it works.

**Comment by starudream** [comment]
@uberhalit it works fine and patch success! Thanks!
