### ISSUE TITLE
Found a way to run the game in full screen with HDR and uncapped frames

### ISSUE THREAD

**Issue by alaa007** [uberhalit/EldenRingFpsUnlockAndMore#32]
This is not an issue but a comment that might help fellow gamers.

As you have noticed when you play the game under borderless full screen, the HDR get disabled and the game looks as ugly as shit.

So playing around, I was able to have 90fps full screen with HDR enabled 2k screen resolution with G-sync enabled.
What I have done:
1- Go to Nvidia Control panel and change the following for Eldin ring in the 3D settings section:
- Set Preferred refresh rate to Highest available
- Set Vertical sync to Off
- Set Power Management to Max performance 
- Set Monitor Technology to G-sync
And make sure to apply
2- Start the game from the patcher and make sure to select the refresh rate. In my case it was 120.
3- Make sure to select borderless full screen to test if the patcher is working fine.
4- Now change the settings to full screen 2k and enable HDR and you will notice its going back to very stable 60 (not like the unpatched game).
5- Quit the game from the menu.
6- Now run the game from steam and dont change anything.
7- Quit the game from the menu.
8- Start the patcher now and you will get a message "Game is already running! Do you want to close and restart in offline mode..."
9- Hit "yes"
10- Patcher will close
11- Open the patcher again and run the game
12- Boom! its full screen with HDR and FPS are not capped!
The down side of my method is that you have to do this every-time from point 6.

I have no idea why this is happening but its working! I told a friend about it and its working fine with him.
**Patcher version is  0.0.0.3-beta**

Please give it a try

**Comment by christofin** [comment]
Damn, this worked for me...but it would be great if the tool just worked in Fullscreen + HDR without this fix

**Comment by Qunka724** [comment]
It's strange, applying those 3D settings in the nvidia control panel actually disables gsync when I launch through steam or the tool. I'm gonna have to experiment with it a bit more - glad this works for you though.

**Comment by christofin** [comment]
Yeah it looks like I'm getting tearing too...maybe the original poster didn't notice this?

**Comment by Qunka724** [comment]
> Yeah it looks like I'm getting tearing too...maybe the original poster didn't notice this?

What's also interesting is I enabled the "G-Sync Compatible Indicator" in the nvidia control panel, and the indicator comes up saying gsync _is_ enabled, but I was getting crazy screen tearing.

**Comment by liquidsnakeblue** [comment]
I'm pretty sure Gsync still requires vsync to be enabled, that's why you're seeing tearing.  Nice that you can get the higher FPS with HDR working but not playable with all that tearing.

**Comment by uberhalit** [comment]
Fullscreen now supports high refresh rates. See #15
