### ISSUE TITLE
'Disable Rune loss on death' leaves your old Runes on the ground.

### ISSUE THREAD

**Issue by SashaFFXIV** [uberhalit/EldenRingFpsUnlockAndMore#33]
This means if you pick them back up after dying you dupe your Runes every time. Needs to either 'retrieve' them upon respawn (like Sekiro) or get rid of them some other way.

**Comment by uberhalit** [comment]
Well yes that's how it works in Elden Ring. I might improve it in the future but for now either disable the feature or don't pick them up...

**Comment by uberhalit** [comment]
With v1.0.0.0 this feature will now prevent Runes from being dropped.
