### ISSUE TITLE
How to actually install?

### ISSUE THREAD

**Issue by Xo1o** [uberhalit/EldenRingFpsUnlockAndMore#35]
I downloaded and unpacked the file from the green "Code" button, but there is no executable. There is a file called EldenRingFpsUnlockAndMore, but that only opens with Microsoft Visual Studio Solution. How do I do the thing?

**Comment by Quzga** [comment]
Click on the .exe here https://github.com/uberhalit/EldenRingFpsUnlockAndMore/releases/tag/0.0.0.4

**Comment by uberhalit** [comment]
![Unbenannt](https://user-images.githubusercontent.com/19159295/155884404-9e895ef7-6db9-4fe0-9497-ce4225654dad.PNG)

**Comment by Xo1o** [comment]
Thanks for the quick reply. I googled how to dl stuff from github and the Code button was suggested, so I thought those were all the files. I appreciate your work.
