### ISSUE TITLE
[Question] Fps uncapped, but still around 60?

### ISSUE THREAD

**Issue by DubbleClick** [uberhalit/EldenRingFpsUnlockAndMore#38]
So, this is a weird issue that I wouldn't attribute to the launcher but to the game - while unlocking fps does unlock fps and it reaches 120-144 in the main menu and sometimes 80-90 in game, it seems that everywhere in the open the game still orients itself around the 60 fps mark? My gpu usage is at around 50% (1440p) instead of being fully utilized. If I play on 4k, gpu usage is around 80-85%, with no decrease in fps.

I assumed the cpu (r9 5950x) to be the bottleneck, but locking cpu speed to 3800mhz or unlocking it to 4900mhz seems to make no difference either. It's as if the game simply waits to stay around 60 fps. Anyone else with the same issue, or a potential fix?

**Comment by Smoukus** [comment]
I have noticed the same thing.

**Comment by uberhalit** [comment]
Should be solved with 0.0.0.5 now. Let me know if it still happens.

**Comment by DubbleClick** [comment]
Game decided to crap itself and bring me down to 0 fps every time I move my mouse after 16 hours of not having that issue, so I guess I'll have to do a fresh windows installation first. Will report back tomorrow.

**Comment by Smoukus** [comment]
Can confirm that with 0.0.0.5 my gpu utilization is now at 93% on average (1440p rx 6800 xt). Seems to be working fine.

**Comment by DubbleClick** [comment]
![image](https://user-images.githubusercontent.com/7896469/155994042-717455ab-8942-4677-bbdd-163b77a5cd48.png)

Works, awesome! Now we just need to hope they fix the stuttering issues.
