### ISSUE TITLE
Error when building latest script in Visual Studio

### ISSUE THREAD

**Issue by phi1m** [uberhalit/EldenRingFpsUnlockAndMore#39]
Error	CS7064	Error opening icon file C:\Users\phili\OneDrive\Desktop\EldenRingFpsUnlockAndMore-main\EldenRingFPSUnlockAndMore\icon.ico -- Could not find file 'C:\Users\phili\OneDrive\Desktop\EldenRingFpsUnlockAndMore-main\EldenRingFPSUnlockAndMore\icon.ico'.

**Comment by DubbleClick** [comment]
name any icon file 'icon.ico' and put it in the folder

**Comment by phi1m** [comment]
Returned with:

Error	CS7065	Error building Win32 resources -- Unable to read beyond the end of the stream.
