### ISSUE TITLE
[feat req] 2 kb/m options analogous to Sekiro

### ISSUE THREAD

**Issue by msoltyspl** [uberhalit/EldenRingFpsUnlockAndMore#4]
1) remove camera auto adjustment
2) remove "camera reset" on target lock/unlock when there is no target

Though there is a minuscule chance they (bamco/from) might fix that later.

**Comment by uberhalit** [comment]
FromSoft won't add these. Yes I am probably going to add them later on.

**Comment by uberhalit** [comment]
Added with v1.1.0.0
