### ISSUE TITLE
[Feature Request] Disable camera adjustments of A/D movement

### ISSUE THREAD

**Issue by DubbleClick** [uberhalit/EldenRingFpsUnlockAndMore#40]
This is by far the most infuriating part about the controls of Elden Ring. When using a mouse you realy don't want automatic camera adjustments in the direction you ride in.

**Comment by uberhalit** [comment]
See #4
And #23
Fixes are planned.

**Comment by DubbleClick** [comment]
Ah that's what they meant with camera auto adjustment
