### ISSUE TITLE
Cant even start the game

### ISSUE THREAD

**Issue by brucebarrera** [uberhalit/EldenRingFpsUnlockAndMore#43]
Followed all the directions for NVidia, opened the unlocker, pressed "Start the game without EAC", screen blinks and app closes...game doesnt launch. Tried copying the .exe to the game folder...still nothing. What am I missing here?
(my game is installed in Steam)
thanks

**Comment by PerfectOua** [comment]
I have the same problem. But I didn't buy the game, if you know what I mean. can you please add button "Start game" like in ver. 0.0.0.4 - it works perfectly.

**Comment by Xbob42** [comment]
Same issue. Game installed on Steam, .4 works but .5 the program just crashes without ever launching the game. Was excited too because we're getting true fullscreen back. Hope it can be fixed soon, love this thing!

**Comment by uberhalit** [comment]
Welp don't push updates at 3 in the morning. Fixed with 0.0.0.5-hotfix1

**Comment by Xbob42** [comment]
Wow, thanks for the quick fix! Hope this didn't keep you from sleeping though...

**Comment by brucebarrera** [comment]
Thanks a lot @uberhalit! I'll test it soon!
