### ISSUE TITLE
Couldn't find game installation path!

### ISSUE THREAD

**Issue by charliik** [uberhalit/EldenRingFpsUnlockAndMore#5]
Getting this error while trying to start the game through your app.

Followed every single step. Twice.
The game is called "eldenring.exe" as mentionned. See here : https://gyazo.com/f65a4b1fba04937495665eb4a3a1c59c

Not-so-legit version
Windows 10 Pro, french language.

Thank you very much for this app and for your time. You're the MVP.

**Comment by badukov** [comment]
[EldenRingFPSUnlockAndMore_v0.0.0.1PathChoosingEdition.zip](https://github.com/uberhalit/EldenRingFpsUnlockAndMore/files/8141695/EldenRingFPSUnlockAndMore_v0.0.0.1PathChoosingEdition.zip)

I added manual folder selection if not found in the registry

**Comment by badukov** [comment]
[EldenRingFPSUnlockAndMore_v0.0.0.1PathChoosingEdition.zip](https://github.com/uberhalit/EldenRingFpsUnlockAndMore/files/8141695/EldenRingFPSUnlockAndMore_v0.0.0.1PathChoosingEdition.zip)

I added manual folder selection if not found in the registry

**Comment by Dacripla** [comment]
Same issue, were you able to figure it out?

**Comment by uberhalit** [comment]
Should be resolved now. Tell me if the selector works.

**Comment by Dacripla** [comment]
> Should be resolved now. Tell me if the selector works.

The game is launching now but it doesnt seem to be going above 60 fps? Game is patched and all?

**Comment by uberhalit** [comment]
> > Should be resolved now. Tell me if the selector works.
> 
> The game is launching now but it doesnt seem to be going above 60 fps? Game is patched and all?

Tick the unlock box and test it in borderless window mode to make sure your monitor isn't forcing 60 Hz.
