### ISSUE TITLE
Non-Native Ultrawide Resolutions in Fullscreen Mode

### ISSUE THREAD

**Issue by joeymetts** [uberhalit/EldenRingFpsUnlockAndMore#52]
Fullscreen is required for HDR in Elden Ring.
Since my use case is streaming the game to my phone, my desired resolution is not the native resolution of my PC.

**Comment by uberhalit** [comment]
So you wan't to set your monitor to a different resolution, use fullscreen and then stream that to your phone? That should be possible, native resolution is meant in your monitor has to natively support it.
