### ISSUE TITLE
Broken animation and physics on certain NPCs

### ISSUE THREAD

**Issue by Desaccorde** [uberhalit/EldenRingFpsUnlockAndMore#57]
I have encountered a physics problem with FPS unlock embedded intp Flawless Widescreen. The birds in Stromveil Castle cannot throw the explosive barrels when you unlock your FPS. There’s just a “poof” animation and the explosive barrels thus stay intact. 

Then I disabled the FPS unlock and the explosions worked again. So it might be breaking some stuff in your gameplay without even realizing.

**Comment by hhamzah99** [comment]
This has already been addressed 

#30
