### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Kursorr** [uberhalit/EldenRingFpsUnlockAndMore#58]
Hi !

I loved your Sekiro mod available on the nexus. Do you plan to add this one also in the Nexus ?

Also, I've read a french new that say your mod can possibly ban the copy of Elden Ring.

```
However, all of these benefits come at a price that some might not be willing to pay. First of all, the use of a special launcher places the game in offline mode. Then, since it contains bonuses that can be interpreted as cheating, the risk of seeing its copy banned by using this mod cannot be excluded.
```

Can you confirm that I can't be ban if i'm using your mod even if i'm playing offline please ?

Last question, maybe stupid but I prefer to be sure ... For playing Elden Ring in offline, I should start Steam on offline mode or an option is available on Elden Ring to play it offline ?

How am I supposed to start the game without EAC and how can I check it's disabled when i'm playing please ?

Thank you so much for your work <3

**Comment by DubbleClick** [comment]
The launcher will automatically start Elden Ring in offline mode without EAC.

There's always a risk of a ban. In every game in history, with every mod in history, there's always a chance to be banned. It's slim, but it's always there.

> how can I check it's disabled when i'm playing please ?

Look up EasyAntiCheat or EasyAntiCheat_EOS Service in your windows services. Should not be running.

**Comment by Bourjois** [comment]
Hi, I wasn't sure where to ask this question, but are you able to disable the auto centring camera? I remember using a mod with Sekiro that enabled true free camera and it was brilliant. The auto centring is causing motion sickness for me and many others.

**Comment by DubbleClick** [comment]
That is not possible (and would be pointless).

**Comment by JWBAK** [comment]
Will using this tool disable the ability to get achievements if I'm only using it for the UW feature?

**Comment by uberhalit** [comment]
> Will using this tool disable the ability to get achievements if I'm only using it for the UW feature?

No it won't.

**Comment by agestrada450** [comment]
> That is not possible (and would be pointless).

It wouldn´t be pointless for me, I have a 750 Ti that doesn´t support DirectX 12 and I get white screen and crash to desktop error, if the game would run using Directx 11 the I could play it. Thanks for answering my question though.

**Comment by DubbleClick** [comment]
Also works through patching RAM and leaves no traces after the game is restarted.
