### ISSUE TITLE
How do i use this to cap the game to 30 fps for lower end pcs?

### ISSUE THREAD

**Issue by Eoaks** [uberhalit/EldenRingFpsUnlockAndMore#59]
Tried setting frame rate lock to 30 but it doesn't seem to be working

**Comment by msoltyspl** [comment]
I'd rather set the limit in your drivers (e.g. in relatively recent nv drivers: ultra latency + fps slider) or via rtss (though no longer needed these days if you just want to set fps), then set the limit in the game to some high/irrelevant value.

**Comment by Lamarcke** [comment]
You should either use RTSS or Scanline Sync x/2.
If you get 30FPS+ consistenly, i recommend using Scanline Sync.

**Comment by dumpsters** [comment]
Does this program unlock the frame rate even if you don't set a value and have the "lock" option unchecked?

**Comment by uberhalit** [comment]
> Does this program unlock the frame rate even if you don't set a value and have the "lock" option unchecked?

No it does not. If you don't check the first checkbox then the game will use FromSofts hardcoded 60fps (and in fullscreen 60Hz) lock.
