### ISSUE TITLE
Run at startup windows and minimize to system tray

### ISSUE THREAD

**Issue by WilliamLeGod** [uberhalit/EldenRingFpsUnlockAndMore#60]
Is it possible to add this feature?:
Run at startup windows and minimize to system tray

**Comment by nickdibart16** [comment]
In order to get it to start with windows, place it in the directory below, just replace "Username" with your windows user name (obviously)
C:\Users\Username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

I am unsure about how to get it to show up in system tray.
