### ISSUE TITLE
Can't get onto 144hz on laptop monitor

### ISSUE THREAD

**Issue by NyLovesYou** [uberhalit/EldenRingFpsUnlockAndMore#64]
The newest version removes the refresh rate lock but my laptop monitor supports 48hz and 144hz. I can't force refresh rate in nvidia settings because my display is tied to my integrated gpu. Maybe implement a way in the unlocker to choose refresh rate?

**Comment by uberhalit** [comment]
Hello, the unlocker does not enforce a Hz lock, you should be able to set the internal display to highest refresh rate, maybe look into the utility of the iGPU. Otherwise you'd need MUX Switch.
