### ISSUE TITLE
Feature request: disable camera auto adjust while moving

### ISSUE THREAD

**Issue by Anyrainel** [uberhalit/EldenRingFpsUnlockAndMore#70]
Thank you so much for enhancing the gameplay for us where FromSoft sucked.

Many players could benefit from this option, see example reddit thread: https://www.reddit.com/r/Eldenring/comments/t12zx6/is_there_any_way_to_turn_off_the_camera/
https://www.reddit.com/r/Eldenring/comments/t0qhyw/auto_centering_camera/

Would appreciate if you can at least look into whether this is possible or not.

**Comment by uberhalit** [comment]
Yes I this is planned, I haven't had the time to reverse the camera part of the engine yet. See #4 , #23

**Comment by mk-hill** [comment]
On the off chance that it's helpful, [here](https://www.patreon.com/posts/elden-ring-mod-0-63320272)'s an example tool someone made which appears to grant complete control over the game's camera. Unfortunately it seems focused solely on providing a photo mode and doesn't offer this kind of gameplay enhancement.

**Comment by samanthar0se** [comment]
I've been doing some research into this over the weekend because I'm one of the people who can't play the game without getting motion sick 😭 

I thought I would share some of the offsets I found in case they help you:

eldenring.exe+3B2CA0 camera vertical adjustment
eldenring.exe+3B2CB3 camera horizontal adjustment
eldenring.exe+3B2D70 camera mouse movement

**Comment by ThinkingFingers** [comment]
I know this is already planned, but man this would be huge for me.

**Comment by FransBouma** [comment]
Seems to be prominent in mouse/kb control but not that much in controller control. The camera system is a matrix copied from the stack (where it was written to by processing code), so it's likely not directly in the camera structure. I couldn't find it. Their spring system for the camera beam seems to be affected constantly by the mouse control which likely causes it, so following the mouse movement call might lead somewhere. The vert/horizontal adjustment code doesn't lead to anything in this area.

**Comment by Delnac** [comment]
If it helps, this cheat table just added it : https://fearlessrevolution.com/viewtopic.php?f=4&t=19378

**Comment by Eerye** [comment]
> If it helps, this cheat table just added it : https://fearlessrevolution.com/viewtopic.php?f=4&t=19378

Oh my god thank fuck for that, the auto follow was so annoying. Though I rather not have CE run in the background when I don't use it for anything else, so I'm still waiting for the feature to get here too.

**Comment by ThinkingFingers** [comment]
> If it helps, this cheat table just added it : https://fearlessrevolution.com/viewtopic.php?f=4&t=19378

Thank you for sharing. I guess the cheat is playing the game without getting sick :D

**Comment by neuro82** [comment]
> If it helps, this cheat table just added it : https://fearlessrevolution.com/viewtopic.php?f=4&t=19378

Awesome, thanks for linking this!

Would love to see the feature added to the FPS unlocker to simplify things but this is a good solution in the meantime

**Comment by techiew** [comment]
I made a mod for this: https://www.nexusmods.com/eldenring/mods/118

**Comment by neuro82** [comment]
> I made a mod for this: https://www.nexusmods.com/eldenring/mods/118
> 
> Works best for kb&m, I will be looking more at the controller drag.

Awesome! Works perfectly, thanks!

**Comment by uberhalit** [comment]
Thanks to [huovnn](https://github.com/huovnn) for his contribution in #84 this is now part of the utility.
