### ISSUE TITLE
Might be just me but game freezes for a few milliseconds whenever the cursor is in movement...

### ISSUE THREAD

**Issue by Eerye** [uberhalit/EldenRingFpsUnlockAndMore#74]
This makes using the mouse really annoying in menus, also the Windows cursor keeps popping in and out while moving the mouse too which isn't much of an issue just weird unless it's related to the freezing.
So I thought I'd ask if it's possible at all for you to alleviate/fix this issue somehow? I kinda doubt From even gives a toss to address this, but I hope I'll be proven wrong.

**Comment by DubbleClick** [comment]
I've had the same, reinstalled Windows and that fixed it. After a while the cursor started becoming the windows cursor for milliseconds, though, but at least no fps stutter when moving mouse no more.

**Comment by Eerye** [comment]
Nice knowing that there's at least one way to get rid of at least the annoying stutter. However, I'd really like a solution to it that doesn't involve reinstalling my whole system. Although I haven't reinstalled it in a few years, I like avoiding it for as long as I can.
Guess I'll just have to bite the bullet if there won't be any other fix, I wanted to give Windows 11 a shot anyway.

Thanks for the reply!

**Comment by DubbleClick** [comment]
Yeah unfortunately I couldn't find anything else to fix it for like three hours. :/
