### ISSUE TITLE
Application shutted down after launching game

### ISSUE THREAD

**Issue by w84gg** [uberhalit/EldenRingFpsUnlockAndMore#8]
LG G SYNC 144 hz + 1080ti + windows 11
Read all your code in main class.
All stages passed, running not licensed steam version with/without steam logging.
I edited registry for true path, game launching but when I switched to your app's window - it just closed after running game, so I even couldn't to patch it (it seems its kind of trick or hack with window activity in PatchGame function that not able for me because main unlock app window closes after running game)

Video is attached!
https://user-images.githubusercontent.com/7249947/155741439-520138c5-bb4b-4392-80be-a581d2863f5d.mp4

**Comment by w84gg** [comment]
> https://user-images.githubusercontent.com/67294769/155742296-9f3bd3fa-b4b0-40ef-8049-1c50e75f405e.png same issue happens when patcher can't find dlls nearby. if that's the actual problem, try build it by yourself or try my build, don't forget to unpack it https://anonfiles.com/x9H4kcKdxe/Debug_zip

![Screenshot_2](https://user-images.githubusercontent.com/7249947/155744730-23355f87-812e-418f-b2e1-58999147b4be.png)
found that inital error

**Comment by sociofall** [comment]
> found that inital error
try launch it as admin

**Comment by w84gg** [comment]
> https://user-images.githubusercontent.com/67294769/155742296-9f3bd3fa-b4b0-40ef-8049-1c50e75f405e.png same issue happens when patcher can't find dlls nearby. if that's the actual problem, try build it by yourself or try my build, don't forget to unpack it https://anonfiles.com/x9H4kcKdxe/Debug_zip

THANK YOU! works after builded!

**Comment by Dacripla** [comment]
> LG G SYNC 144 hz + 1080ti + windows 11 Read all your code in main class. All stages passed, running not licensed steam version with/without steam logging. I edited registry for true path, game launching but when I switched to your app's window - it just closed after running game, so I even couldn't to patch it (it seems its kind of trick or hack with window activity in PatchGame function that not able for me because main unlock app window closes after running game)
> 
> Video is attached! https://user-images.githubusercontent.com/7249947/155741439-520138c5-bb4b-4392-80be-a581d2863f5d.mp4

How do you go about editing the registry so that its directed to my game files? It cant seem to find them
