### ISSUE TITLE
There is a screen freeze problem in 1.02.3

### ISSUE THREAD

**Issue by mr30tapkill** [uberhalit/EldenRingFpsUnlockAndMore#81]
It ran very well yesterday. I wanted to try the online mode this morning, so I didn't use the software before entering the game, and then I quit the game when I couldn't stand 60hz. After reusing the software, I entered the game and it became abnormally stuck.

2080 ti
i9-10900k
144hz

**Comment by mr30tapkill** [comment]
but 60fps so smoothy

**Comment by Loban79** [comment]
> but 60fps so smoothy

No
