### ISSUE TITLE
Issue with new version 1.03

### ISSUE THREAD

**Issue by valentinvisintin** [uberhalit/EldenRingFpsUnlockAndMore#82]
There's some weird display on the right side of the screen when using v1.0.0.1 of the mod with the 1.03 of the game

**Comment by quarrel** [comment]
Working perfect for me on 1.03.

I suspect your gfx issue isn't related to this.

**Comment by valentinvisintin** [comment]
Yeah i tried without mod, and still have a this weird display on the right side of the screen
