### ISSUE TITLE
Software opens, then freezes instantly

### ISSUE THREAD

**Issue by cwil007** [uberhalit/EldenRingFpsUnlockAndMore#86]
Tried running the game without unlocker on, restarting PC, redownloading, steam in offline mode, and unplugging ethernet. It was working fine yesterday as well, not sure what's going on...

**Comment by uberhalit** [comment]
As it was working fine a day before I am assuming that is something on your side.

**Comment by lurch9** [comment]
To fix this, move the .exe out of your downloads folder. I moved mine to my desktop and it immediately started working again.
