### ISSUE TITLE
Disabling Fullscreen optimizations

### ISSUE THREAD

**Issue by Deniz1433** [uberhalit/EldenRingFpsUnlockAndMore#96]
Not related at all to your program, but even when I check "disable fullscreen optimizations" AND have the registry change that makes Windows actually care about that tick, the game still doesn't run in fullscreen exclusive (I checked it by changing the volume and seeing that the overlay actually show up on the top left, FSE works for other games I have so it's about Elden Ring) Anybody knows how to fix this?

**Comment by uberhalit** [comment]
There is no true exclusive fullscreen on DX12 games, DX12 fullscreen works different than DX11. Windows overlays like sound popup and notifications will always be shown without minimizing.

**Comment by Deniz1433** [comment]
Hey, thanks for letting me know about that. So with the DX11 patch it can work
