### ISSUE TITLE
user.config

### ISSUE THREAD

**Issue by o0Julia0o** [uberhalit/EldenRingFpsUnlockAndMore#98]
Hello, 

placing the `user.config` file into appdata is technically not done by the utility itself but by Microsoft. MS recommends using AppData since Windows 8. I had the config file next to the exe in my Sekiro-Utility. About 1-2x times per week users complained that the utility wouldn't save any settings, this went on for 2 years. Mostly because people had started the utility from inside an archive without properly extracting it, some others launched it from a write-protected folder and so on.

_Originally posted by @uberhalit in https://github.com/uberhalit/EldenRingFpsUnlockAndMore/issues/89#issuecomment-1076729486_

So an option would be the solution. Default = AppData, option set = next to the exe.

**Comment by uberhalit** [comment]
That would require a custom config handler and a lot of boilerplate code and goes against Microsofts coding guidelines. I am sorry but I am not going to spend development time on something like this, there are a lot of other issues that have priority.

**Comment by o0Julia0o** [comment]
ok thank you. It´s your Tool, so you are free to do so. But keep in mid, you are free to don´t hassle around with Microsoft-commands.
